// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using twitter_feed_server.DB;

#nullable disable

namespace twitter_feed_server.Migrations
{
    [DbContext(typeof(TwitterDbContext))]
    [Migration("20240405050550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("twitter_feed_server.Models.Tweet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Analytics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Retweets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TweetBody")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tweets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@adam435",
                            Likes = 100,
                            Name = "Adam",
                            Retweets = 1,
                            TweetBody = "me after 1 double rum and diet",
                            Verified = false
                        },
                        new
                        {
                            Id = 2,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@kevin6745",
                            Likes = 100,
                            Name = "Kevin",
                            Retweets = 2,
                            TweetBody = "\"My friend thinks over there you cute\" The friend:",
                            Verified = true
                        },
                        new
                        {
                            Id = 3,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@elon765",
                            Likes = 100,
                            Name = "Elon",
                            Retweets = 3,
                            TweetBody = "The double hands in the pocket",
                            Verified = false
                        },
                        new
                        {
                            Id = 4,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@andrew325",
                            Likes = 100,
                            Name = "Andrew",
                            Retweets = 4,
                            TweetBody = "(your text here)",
                            Verified = false
                        },
                        new
                        {
                            Id = 5,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@robert333",
                            Likes = 100,
                            Name = "Robert",
                            Retweets = 5,
                            TweetBody = "Relatives: What a strong handsome young man you've become... 12 y/o me:",
                            Verified = false
                        },
                        new
                        {
                            Id = 6,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@jessica6565",
                            Likes = 100,
                            Name = "Jessica",
                            Retweets = 6,
                            TweetBody = "Me leaving the pot in the sink because \"it needs to soak\"",
                            Verified = false
                        },
                        new
                        {
                            Id = 7,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@pam76676",
                            Likes = 100,
                            Name = "Pam",
                            Retweets = 7,
                            TweetBody = "me, when I show up on my day off",
                            Verified = false
                        },
                        new
                        {
                            Id = 8,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@leo8767",
                            Likes = 100,
                            Name = "Leo",
                            Retweets = 8,
                            TweetBody = "watching someone else get blamed for your fart",
                            Verified = true
                        },
                        new
                        {
                            Id = 9,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@rachel7777",
                            Likes = 100,
                            Name = "Rachel",
                            Retweets = 9,
                            TweetBody = "NO ONE: YOUR PARENTS FAMILY PHOTOS",
                            Verified = false
                        },
                        new
                        {
                            Id = 10,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@mohammad0909",
                            Likes = 100,
                            Name = "Mohammad",
                            Retweets = 10,
                            TweetBody = "My dog when I pick up a poo bag",
                            Verified = false
                        },
                        new
                        {
                            Id = 11,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@raj7878",
                            Likes = 100,
                            Name = "Raj",
                            Retweets = 11,
                            TweetBody = "Did you clog the toilet again?? Me:",
                            Verified = false
                        },
                        new
                        {
                            Id = 12,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@daniel9343",
                            Likes = 100,
                            Name = "Daniel",
                            Retweets = 12,
                            TweetBody = "How many memes did you post today? ME:",
                            Verified = false
                        },
                        new
                        {
                            Id = 13,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@jake3409",
                            Likes = 100,
                            Name = "Jake",
                            Retweets = 13,
                            TweetBody = "smurk and shrug",
                            Verified = true
                        },
                        new
                        {
                            Id = 14,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@hunter5326",
                            Likes = 100,
                            Name = "Hunter",
                            Retweets = 14,
                            TweetBody = "me when my friend posts a screenshot of our text messages on their story so everyone can see how funny i am",
                            Verified = false
                        },
                        new
                        {
                            Id = 15,
                            Analytics = 101,
                            Comments = 10,
                            Handle = "@sukh367",
                            Likes = 100,
                            Name = "Sukhpreet",
                            Retweets = 15,
                            TweetBody = "Everywhere I go....",
                            Verified = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
